export interface TrendingItem {
  duration: number;
  thumbnail: string;
  title: string;
  uploadedDate: string;
  uploaderAvatar: string;
  uploaderName: string;
  uploaderUrl: string;
  uploaderVerified: boolean;
  url: string;
  views: number;
}

export interface VideoDetails {
  id: string;
  title: string;
  description: string;
  views: number;
  likes: number;
  dislikes: number;
  comments: number;
}

export interface AudioStream {
  bitrate: number;
  codec: string;
  format: string;
  indexEnd: number;
  indexStart: number;
  initStart: number;
  initEnd: number;
  mimeType: string;
  quality: string;
  url: string;
  videoOnly: boolean;
}

export interface VideoStream {
  bitrate: number;
  codec: string;
  format: string;
  fps: number;
  height: number;
  indexEnd: number;
  indexStart: number;
  initStart: number;
  initEnd: number;
  mimeType: string;
  quality: string;
  url: string;
  videoOnly: boolean;
  width: number;
}

export interface Subtitle {
  autoGenerated: boolean;
  code: string;
  mimeType: string;
  name: string;
  url: string;
}

export interface RelatedStream {
  duration: number;
  thumbnail: string;
  title: string;
  uploadedDate: string;
  uploaderAvatar: string;
  uploaderUrl: string;
  uploaderVerified: boolean;
  url: string;
  views: number;
  uploaderName: string;
}

export interface VideoStreamsResponse {
  audioStreams: AudioStream[];
  dash: string | null;
  description: string;
  dislikes: number;
  duration: number;
  hls: string | null;
  lbryId: string;
  likes: number;
  livestream: boolean;
  proxyUrl: string;
  relatedStreams: RelatedStream[];
  subtitles: Subtitle[];
  thumbnailUrl: string;
  title: string;
  uploadDate: string;
  uploader: string;
  uploaderUrl: string;
  uploaderVerified: boolean;
  videoStreams: VideoStream[];
  views: number;
  uploaderAvatar: string;
  uploaderSubscriberCount: string;
}

export interface SearchItem {
  url: string;
  type: "channel" | "stream";
  name?: string;
  title?: string;
  thumbnail: string;
  description?: string;
  shortDescription?: string;
  uploaderName?: string;
  uploaderUrl?: string;
  uploaderAvatar?: string;
  uploadedDate?: string;
  duration?: number;
  views?: number;
  subscribers?: number;
  videos?: number;
  verified?: boolean;
  uploaderVerified?: boolean;
  isShort?: boolean;
}

export interface SearchResponse {
  items: SearchItem[];
  nextpage?: string;
  suggestion?: string;
  corrected?: boolean;
}

export interface SuggestionsResponse extends Array<string | string[]> {
  0: string; // The original query
  1: string[]; // List of suggestions
}

export interface ChannelResponse {
  avatarUrl: string;
  bannerUrl: string;
  description: string;
  id: string;
  name: string;
  nextpage: string;
  relatedStreams: RelatedStream[];
  subscriberCount: number;
  verified: boolean;
}
